---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: get podman executable path
      command: which podman
      changed_when: false
      register: podman_path

    - name: save path to executable as fact
      set_fact:
        podman_cmd: "{{ podman_path.stdout }}"

    - name: Create podman container(s)
      containers.podman.podman_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        privileged: "{{ item.privileged | default(false) }}"
        command: "{{ item.command | default(omit) }}"
        cap_add: "{{ item.capabilities | default(omit) }}"
        volumes: "{{ item.volumes | default(omit) }}"
        cgroupns: "{{ item.cgroupns_mode | default(omit) }}"
        security_opt: "{{ item.security_opt | default(omit) }}"
        env: "{{ item.env | default(omit) }}"
        hostname: "{{ item.hostname | default(item.name) }}"
        ports: "{{ item.ports | default(omit) }}"
        etc_hosts: "{{ etc_hosts | default(omit) }}"
        network: "{{ item.network | default(omit) }}"
        tmpfs: "{{ item.tmpfs | default(omit) }}"
        ulimit: "{{ item.ulimits | default(omit) }}"
      register: server
      loop: "{{ molecule_yml.platforms }}"

    - name: Populate instance config dict
      set_fact:
        instance_conf_dict: {
          'instance': "{{ item.item.name }}",
          'address': "{{ item.container.Id }}",
          'user': 'root',
          'port': '0',
          'password': '',
          'connection': 'podman'
        }
      register: instance_config_dict
      loop: "{{ server.results }}"
      loop_control:
        label: "{{ item.item.name }}"

    - name: Convert instance config dict to a list
      set_fact:
        instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"

    - name: Dump instance config
      copy:
        content: |
          # Molecule managed

          {{ instance_conf | to_nice_yaml }}
        dest: "{{ molecule_instance_config }}"
      when: server.changed | bool
