---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Destroy podman container(s)
      containers.podman.podman_container:
        name: "{{ item.name }}"
        state: absent
        force_delete: true
      register: server
      loop: "{{ molecule_yml.platforms }}"

    - name: Remove instance config
      file:
        path: "{{ molecule_instance_config }}"
        state: absent
      when: server.changed | bool
