---
driver:
  name: podman

provisioner:
  name: ansible
  inventory:
    host_vars:
      ubuntu-24.04:
        nomad_node_role: both

scenario:
  name: ubuntu-24.04
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy

platforms:
  - name: ubuntu-24.04
    groups:
      - nomad_instances
    image: dokken/ubuntu-24.04
    dockerfile: ../_shared/Dockerfile.j2
    capabilities:
      - SYS_ADMIN
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    command: /bin/systemd
